### ISSUE TITLE
Support for accounts that are associated with multiple teams

### ISSUE THREAD

**Issue by lemonmojo** [macmade/Notarize#2]
Currently, the app doesn't work when using an Apple ID that is associated with multiple teams. At sign-in an error is reported: ```Your Apple ID account is also attached to other iTunes providers. You will need to create a new user on iTunes Connect to submit content to this account. Please contact us if you have questions or need help.```

To work around this you would need to allow passing the `--asc-provider <provider_shortname>` parameter to altool.

The `provider_shortname` can be retrieved by running `/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter -m provider -u 'APPLE_ID' -p 'APP_SPECIFIC_PW' -account_type itunes_connect -v off`.

**Comment by macmade** [comment]
Thanks a lot for this report.

I can support this, but I've got a few questions, since I'm not familiar with this type of account.

When passing `--asc-provider` to `altool`, I guess the username and passwords are still mandatory.  
Can you confirm this?

Is there only one `asc-provider` per account, or is it possible that `iTMSTransporter` returns multiple ones?

**Comment by lemonmojo** [comment]
> When passing `--asc-provider` to `altool`, I guess the username and passwords are still mandatory.
Can you confirm this?

Yes!

> Is there only one `asc-provider` per account, or is it possible that `iTMSTransporter` returns multiple ones?

If your account is member in multiple teams, it returns all of them. For instance, my account is part of 2 teams and `iTMSTransporter` returns:
```
Provider listing:
   - Long Name -		- Short Name -
1  ACCOUNTNAME|NUMBER  		ACCOUNTNAMENUMBER
2  ACCOUNTNAME2		        NUMBER2
```

**Comment by macmade** [comment]
Thank you, I’ll try to make this work this weekend.

**Comment by canalnoises** [comment]
@macmade, did you ever have a chance to look into this? Notarize looks like a great tool but my account is also part of two teams, so I'm not able to log in.

**Comment by macmade** [comment]
I looked into it, but haven't found the time to implement it correctly yet.
Unfortunately I'm quite busy right now, so don't know when I'll be able to do it.

**Comment by canalnoises** [comment]
Fair enough. Thanks for the response :)

**Comment by macmade** [comment]
As of version 1.2.0, you can now specify a provider short name for your account.
