### ISSUE TITLE
altool not available error

### ISSUE THREAD

**Issue by henhouse** [macmade/Notarize#3]
I receive the "altool is not available" splash when running the app, despite having that tool and Xcode installed.

Self-building the app seems to reveal this error when the xcrun altool --help is run:

> 2021-10-08 14:44:28.595133+0200 xcrun[5965:4812179] Failed to open macho file at /Applications/Xcode.app/Contents/Developer/usr/bin/altool for reading: Too many levels of symbolic links

However, just below it is the output of the altool --help. So it does indeed seem to execute, but this error or warning seems to potentially throw it off.

Running macOS 11.6 with Xcode 13.0

**Comment by macmade** [comment]
Thanks for reporting this.

I just made version 1.1.2 available, with Xcode 13 support.  
The issue should now be fixed.

Closing for now, please reopen if you still have issues.
